export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";

export const PAYPAL_INITIATE_PAYMENT_REQUEST =
  "PAYPAL_INITIATE_PAYMENT_REQUEST";
export const PAYPAL_INITIATE_PAYMENT_SUCCESS =
  "PAYPAL_INITIATE_PAYMENT_SUCCESS";
export const PAYPAL_INITIATE_PAYMENT_FAIL = "PAYPAL_INITIATE_PAYMENT_FAIL";

export const PAYPAL_CONFIRM_PAYMENT_REQUEST = "PAYPAL_CONFIRM_PAYMENT_REQUEST";
export const PAYPAL_CONFIRM_PAYMENT_SUCCESS = "PAYPAL_CONFIRM_PAYMENT_SUCCESS";
export const PAYPAL_CONFIRM_PAYMENT_FAIL = "PAYPAL_CONFIRM_PAYMENT_FAIL";
